### ISSUE TITLE
Escape button doesn't work well on MacOS

### ISSUE THREAD

**Issue by catlilface** [zen-browser/theme-components#14]
floating input field collapses on escape button, but it doesn't disappear

**Comment by PRITHIVEE** [comment]
For me on hitting on Escape the URL bar keeps Focus and requires another click action in the main content page in order for it to disappear
I have enabled "Hide the top toolbar as well in compact mode"

**Comment by mr-cheffy** [comment]
This is because it's still focused on the URL bar, in order to make it hide, unfocus the element by clicking on other elements or the website
