### ISSUE TITLE
remove browser padding doen't work in compact mode

### ISSUE THREAD

**Issue by phanthm** [zen-browser/theme-components#19]
![image](https://github.com/user-attachments/assets/fd253077-e5ba-4195-b902-74bd16cc90dd)

**Comment by mr-cheffy** [comment]
This is not the place for these bugs, please report it to the original author

**Comment by bonnebulle** [comment]
Sorry but 
![image](https://github.com/user-attachments/assets/f560791f-3151-46f3-9bcb-8200f0145715)
Homepage pointing here...
Am searching for the same issue resolution...
there is extra padding arround the Zen browser 
![image](https://github.com/user-attachments/assets/a97cb137-7b9c-4f3b-9e3f-6537011f4c5b)
