### ISSUE TITLE
[No browser padding] - Padding is not applied to the right sidebar

### ISSUE THREAD

**Issue by Yuzuctus** [zen-browser/theme-components#2]
When the sidebar is on the left, the padding on the right is removed (see image below).
![image](https://github.com/user-attachments/assets/7198f22c-e620-4751-99e3-14b0ef9c92d1)

But when the sidebar is on the left, the padding appears on the left, so the theme is not correctly applied for all configurations.
The corner of the sidebar is not correctly applied either
![image](https://github.com/user-attachments/assets/3732292d-cc0c-46b7-bc24-a6d044e73f28)

**Comment by mr-cheffy** [comment]
This will be fixed for next Zen release 👍🏽
