### ISSUE TITLE
Adding Remove Browser Padding removes rounded corners as well 

### ISSUE THREAD

**Issue by astro-ray** [zen-browser/theme-components#3]
After installing the `Remove Browser Padding` theme it removed the corner radius

![image](https://github.com/user-attachments/assets/2589b6ff-f2ac-42a0-9dea-bc70b58b7732)
![Screenshot from 2024-08-20 10-40-07](https://github.com/user-attachments/assets/4b8e81a9-c7dc-4d83-abd2-b5fe11270675)

I would expect the corner radius would remain unchanged

**Comment by mr-cheffy** [comment]
This will be fixed for the next zen release!
