### ISSUE TITLE
Floating url bar isn't centered

### ISSUE THREAD

**Issue by ThePixelDude111** [zen-browser/theme-components#30]
Whenever I click on the bar it pops up on the right side, like this:
![Screenshot (18)](https://github.com/user-attachments/assets/f8cf33aa-f963-4c46-a61c-f453d9ba1a4c)

I'm on the latest version of zen (1.0.1-a2)
My monitor resolution is 1366x768
I'm on windows 10 22h2

**Comment by NyllRE** [comment]
same issue, it's hidden on the side to me, too far out. 1920x1080

**Comment by audrNa** [comment]
yeah um im in pain (1920x1080)
![Screenshot 2024-09-18 215120](https://github.com/user-attachments/assets/b777941b-ebea-4d75-8b8d-c9d753e7407d)

**Comment by ThePixelDude111** [comment]
Edit: After I updated the themes in zen settings today, it got fixed.
Marking as closed.
