### ISSUE TITLE
no-padding retains 1px outline which makes mouse scrolling fail at the edges

### ISSUE THREAD

**Issue by LivResonata** [zen-browser/theme-components#33]
Zen Version: 1.0.1-a.5 (Appimage; Linux)
Effected since: 1.0.1-a.3
Component: no-padding (v1.0.2)

There is a one pixel outline that surrounds the webpage view that does not go away when using said component.
This makes scrolling via cursor fail when moving the mouse all the way to the sides.
Effects both left or right tab bar setting.

Oddly though, when correcting the cursor to hit the scrollbar and once it is let go with the cursor still in it, the scroll bar can still be clicked.

Provided screenshots below:
- Tab bar at the left; screencap showing right side
![Screenshot_20240925_132619](https://github.com/user-attachments/assets/1be33456-5c3e-403d-8bd8-63c8ea4f11cf)
- Tab bar at the right; screencap showing left side
![Screenshot_20240925_132637](https://github.com/user-attachments/assets/daa28296-2c10-46a3-b6ad-271b15d14475)

**Comment by MrinmoyHaloi** [comment]
Yeah, it's happening with my browser too. It's an annoying issue

**Comment by LivResonata** [comment]
Closing as the bug has been fixed. No changes to the mod was made nor needed.

To fix, simply update the browser; or use Zen version `1.0.1-a.15` or above.
As of writing, the bug has not resurfaced in the current latest version.

Fixed since Zen version: 1.0.1-a.15
Still working as of: 1.0.1-a.18
Component: no-padding (v1.0.2)
