### ISSUE TITLE
Have you considered adding blur to the Floating URLbar?

### ISSUE THREAD

**Issue by hoachnt** [zen-browser/theme-components#6]

**Comment by bazixv13** [comment]
this is the theme repo. future requests referring to the Zen browser should be reported [there](https://github.com/zen-browser/desktop/issues) 🧐

**Comment by hoachnt** [comment]
> this is the theme repo. future requests referring to the Zen browser should be reported [there](https://github.com/zen-browser/desktop/issues) 🧐

Oh, ok thanks
