### ISSUE TITLE
Floating URLbar - Select text when link is clicked

### ISSUE THREAD

**Issue by Car0lina5** [zen-browser/theme-components#9]
Hello! I don't know if it's just a problem with me or if it's just supposed to be like this. But is it possible that when we click on the link it will all be selected? In my opinion, this selection doesn't work that well and isn't very practical. Thanks!

https://github.com/user-attachments/assets/e5114599-cc98-4fc4-a57e-56381492b3d6

**Comment by shahriaar0** [comment]
I've had to keep the extension disabled because of this issue as well.

**Comment by mr-cheffy** [comment]
https://github.com/zen-browser/theme-components/issues/1
